import {
  pgTable,
  serial,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

export const transactions = pgTable("transactions", {
  id: serial("id").primaryKey(),
  documentType: text("document_type"),
  department: text("department"),
  searchPeriod: text("search_period"),
  subRegistrarOffice: text("sub_registrar_office"),
  surveyNumbers: text("survey_numbers"),
  houseNumber: text("house_number"),
  propertyType: text("property_type"),
  propertyTypeTamil: text("property_type_tamil"),
  village: text("village"),
  villageTamil: text("village_tamil"),
  recordedTransaction: text("recorded_transaction"),
  recordedTransactionTamil: text("recorded_transaction_tamil"),
  documentNumber: text("document_number"),
  registeredDate: text("registered_date"),
  executionDate: text("execution_date"),
  landExtent: text("land_extent"),
  landExtentTamil: text("land_extent_tamil"),
  buyerName: text("buyer_name"),
  sellerName: text("seller_name"),
  partyName: text("party_name"),
  partyNameTamil: text("party_name_tamil"),
  buyerNameTamil: text("buyer_name_tamil"),
  sellerNameTamil: text("seller_name_tamil"),
  fullText: text("full_text"),
  fullTextTamil: text("full_text_tamil"),
  createdAt: timestamp("created_at").defaultNow(),
});